_core:
  default_config_hash: nS-G7Is2pUbuItsDst0AbnICh25x6m3ID0MmgM0mkrc
govuk_breadcrumb: 1
search_box: 1
govuk_cookie: 1
govuk_phase_banner: prototype
phase_banner_message:
  value: '<p>This is a new service â€“ your <a class="govuk-link" href="/contact/feedback">feedback</a> will help us to improve it.</p>'
  format: full_html
features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
govuk_cookie_name: _cookie_policy
govuk_cookie_policy:
  analytics: analytics
  functional: functional
  other: other
